# _BASE_: "/media/data/ccr/liutieCompressAI/VCM/configs/Base-RCNN-FPN-VCM.yaml" #vivo
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "/media/data/ccr/zzf/zzf_save/output/EXP_cheng2020anchor_256chinput_P2inP2P3P4P5outMSE_P2zeroyouxiajiao256_lambda8_N192_5Wtrain_eachdnorm_01061340/model_0039999.pth"


  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101


DATASETS:
  TRAIN: ("openimg_train",)
  TEST: ()


OUTPUT_DIR: ../../zzf_save/output/EXP_cheng2020anchor_256chinput_P2down2345inout
SOLVER:
  STEPS: (130000, 180000)
  MAX_ITER: 250000
  CHECKPOINT_PERIOD: 5000 #默认是5000
  IMS_PER_BATCH: 8 #8 #1 #4 #6
INPUT:
  MIN_SIZE_TRAIN: (800, 800)
# # MIN_SIZE_TEST: 400
